/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare namespace external {
  export class Compiler {
    constructor()
  }
}
export declare namespace reference {
  export class Compiler {
    constructor(compilation: Compilation)
  }
  export class Compilation {
    constructor()
  }
}
