/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export declare namespace external {
  export class Compiler {
    constructor()
    createCompilation(): ExternalObject<Compilation>
  }
}
export declare namespace reference {
  export class Compiler {
    constructor(compilation: Compilation)
  }
  export class Compilation {
    constructor()
  }
}
