/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export declare namespace external {
  export class Compiler {
    constructor()
    createCompilation(): ExternalObject<Compilation>
  }
}
export declare namespace reference {
  export class Compiler {
    constructor(compilation: Compilation)
  }
  export class Compilation {
    constructor()
  }
}
export declare namespace value {
  export interface Counter {
    cnt: number
  }
  export function createCounter(init: number): Counter
}
export declare namespace _class {
  export class Counter {
    cnt: number
    constructor(init: number)
    add(by: number): number
    get(): number
  }
}
